from qiskit import QuantumCircuit
grover = QuantumCircuit(9,9)
grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.x(0)
grover.h(0)


#define U_f

grover.x(1)
grover.x(3)
grover.x(4)
grover.ccx(4,5,6)
grover.ccx(3,6,7)
grover.ccx(2,7,8)
grover.ccx(1,8,0)
grover.ccx(2,7,8)
grover.ccx(3,6,7)
grover.ccx(4,5,6)
grover.x(1)
grover.x(3)
grover.x(4)
grover.barrier()

#define W

grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.x(1)
grover.x(2)
grover.x(3)
grover.x(4)
grover.x(5)
grover.ccx(4,5,6)
grover.ccx(3,6,7)
grover.ccz(2,7,1)
grover.ccx(3,6,7)
grover.ccx(4,5,6)
grover.x(1)
grover.x(2)
grover.x(3)
grover.x(4)
grover.x(5)
grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.barrier()

grover.x(1)
grover.x(3)
grover.x(4)
grover.ccx(4,5,6)
grover.ccx(3,6,7)
grover.ccx(2,7,8)
grover.ccx(1,8,0)
grover.ccx(2,7,8)
grover.ccx(3,6,7)
grover.ccx(4,5,6)
grover.x(1)
grover.x(3)
grover.x(4)
grover.barrier()

grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.x(1)
grover.x(2)
grover.x(3)
grover.x(4)
grover.x(5)
grover.ccx(4,5,6)
grover.ccx(3,6,7)
grover.ccz(2,7,1)
grover.ccx(3,6,7)
grover.ccx(4,5,6)
grover.x(1)
grover.x(2)
grover.x(3)
grover.x(4)
grover.x(5)
grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.barrier()


grover.x(1)
grover.x(3)
grover.x(4)
grover.ccx(4,5,6)
grover.ccx(3,6,7)
grover.ccx(2,7,8)
grover.ccx(1,8,0)
grover.ccx(2,7,8)
grover.ccx(3,6,7)
grover.ccx(4,5,6)
grover.x(1)
grover.x(3)
grover.x(4)
grover.barrier()

grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.x(1)
grover.x(2)
grover.x(3)
grover.x(4)
grover.x(5)
grover.ccx(4,5,6)
grover.ccx(3,6,7)
grover.ccz(2,7,1)
grover.ccx(3,6,7)
grover.ccx(4,5,6)
grover.x(1)
grover.x(2)
grover.x(3)
grover.x(4)
grover.x(5)
grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.barrier()

grover.x(1)
grover.x(3)
grover.x(4)
grover.ccx(4,5,6)
grover.ccx(3,6,7)
grover.ccx(2,7,8)
grover.ccx(1,8,0)
grover.ccx(2,7,8)
grover.ccx(3,6,7)
grover.ccx(4,5,6)
grover.x(1)
grover.x(3)
grover.x(4)
grover.barrier()


grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.x(1)
grover.x(2)
grover.x(3)
grover.x(4)
grover.x(5)
grover.ccx(4,5,6)
grover.ccx(3,6,7)
grover.ccz(2,7,1)
grover.ccx(3,6,7)
grover.ccx(4,5,6)
grover.x(1)
grover.x(2)
grover.x(3)
grover.x(4)
grover.x(5)
grover.h(1)
grover.h(2)
grover.h(3)
grover.h(4)
grover.h(5)
grover.barrier()

grover.measure_all()

from qiskit_aer import Aer
backend = Aer.get_backend('aer_simulator')
from qiskit import transpile
from qiskit_aer import AerSimulator
from qiskit.visualization import plot_histogram, plot_state_city
import qiskit.quantum_info as qi
simulator = AerSimulator()
grover = transpile(grover, simulator)
result = simulator.run(grover).result()
counts = result.get_counts(grover)
plot_histogram(counts, title='grover')
print(counts)


